CREATE TABLE `test`.`gold_msg` 
(`GOLD_MSG_num` INT(11) NOT NULL AUTO_INCREMENT COMMENT '고유번호' , 
`GOLD_MSG_name` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '메세지 작성자' ,
`GOLD_MSG_email` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '작성자 이메일' ,
`GOLD_MSG_tit` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '메세지 제목' ,
`GOLD_MSG_con` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '메세지 내용' ,
`GOLD_MSG_reg` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '작성일자' ,
 PRIMARY KEY (`GOLD_MSG_num`)) ENGINE = InnoDB;